server:
  port: 8222
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:

        - id: commande-service
          uri: lb:http://ORDER-SERVICE
          predicates:
            - Path=/api/v1/commandes/**
        - id: order-lines-service
          uri: lb:http://COMMANDE-SERVICE

        - id: produit-service
          uri: lb:http://PRODUIT-SERVICE
          predicates:
            - Path=/api/v1/produits/**

